name: GuardianPay MLOps Pipeline

on:
  push:
    branches: [ main ]  # Runs every time you 'git push' to the main branch
  pull_request:
    branches: [ main ]

jobs:
  quality-control:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Unit Tests
        run: pytest tests/  # Ensures your API isn't broken

  build-and-deploy:
    needs: quality-control  # Only runs if the tests pass
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Images
        run: docker-compose build

      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push to Registry
        run: |
          docker tag src-backend:latest ${{ secrets.DOCKER_USERNAME }}/guardian-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/guardian-backend:latest