name: GuardianPay MLOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality-control:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        # Changed: We set the working directory so pip finds your requirements.txt
        working-directory: ./src
        run: pip install -r requirements.txt

      - name: Run Unit Tests
        working-directory: ./src
        env:
          # NEW: Tells MLflow where the local database is
          MLFLOW_TRACKING_URI: sqlite:///mlflow.db
        run: |
          pip install pytest pytest-asyncio httpx
          # NEW: Adds the current directory (.) to the Python path so tests find main.py
          export PYTHONPATH=$PYTHONPATH:.
          python -m pytest tests/

  build-and-deploy:
    needs: quality-control
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code # Important: Need to checkout code again for the second job
        uses: actions/checkout@v3

      - name: Build Docker Images
        # Changed: Point to the folder where docker-compose.yml lives
        working-directory: ./src
        run: docker-compose build

      - name: Log into Docker Hub
        if: success() # Only log in if build succeeds
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push to Registry
        working-directory: ./src
        run: |
          docker tag src-backend:latest ${{ secrets.DOCKER_USERNAME }}/guardian-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/guardian-backend:latest